### ISSUE TITLE
Not compressing PNG images on Firefox

### ISSUE THREAD

**Issue by jonnym1** [ayastreb/bandwidth-hero#13]
Not compressing PNG images on latest version of Firefox, Works OK on latest version of chrome.

Open any webpage with PNG images on it in Firefox 58 with bandwidth hero 2.0.2 and you will see they are in colour and uncompressed while jpeg images are in greyscale.

**Comment by jonnym1** [comment]
Its because firefox does not support the webp format.

**Comment by ayastreb** [comment]
Yes, if browser does not support webp - the proxy will only convert PNG files larger than 100KB. It will convert them to JPEG, which replaces transparent areas with black background.
