### ISSUE TITLE
Captcha Loading

### ISSUE THREAD

**Issue by chessgeniusc2** [ayastreb/bandwidth-hero#2]
In order to get the correct Captcha we have to manually disable the extension on certain sites. So it would be better if we could have something like "whitelist" or "add to white list" .

**Comment by ayastreb** [comment]
Hi @chessgeniusc2 
whitelist was added in the latest extension release (1.1.0). You can now add hostnames to whitelist and images from that host will not be compressed.
Please, let me know if that helps you!

**Comment by fogoat** [comment]
How do you add host names to white list?  For Google reCaptcha, bandwidth hero works fine. SolveMedia it doesn't work. And other basic captcha (don't know the company) doesn't work.
