### ISSUE TITLE
Need help building from the source in Windows

### ISSUE THREAD

**Issue by chella1cm** [ayastreb/bandwidth-hero#36]
I am trying to build the extension from the source but I keeping running into errors. I am following ur instructions for Ubuntu, thats the reason I guess, Can I get instructions for Windows? I am using Windows 10. 
Also, I have been using ur addon Firefox addon, with a Heroku hosting. Really great addon.

**Comment by mandaputtra** [comment]
What are your errors?

**Comment by chella1cm** [comment]
> 
> 
> What are your errors?

Very sorry.. for not including it. This is the error I got when I tried to test it...

```
C:\Users\Chella\Desktop\bandwidth-hero>npm test

> bandwidth-hero-extension@2.1.4 test C:\Users\Chella\Desktop\bandwidth-hero
> NODE_ENV=test jest

'NODE_ENV' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! Test failed.  See above for more details.
```
This when I tried to build it.
```

`C:\Users\Chella\Desktop\bandwidth-hero>npm run build

> bandwidth-hero-extension@2.1.4 build C:\Users\Chella\Desktop\bandwidth-hero
> NODE_ENV=production webpack --env.NODE_ENV=production -p

'NODE_ENV' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bandwidth-hero-extension@2.1.4 build: `NODE_ENV=production webpack --env.NODE_ENV=production -p`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bandwidth-hero-extension@2.1.4 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Chella\AppData\Roaming\npm-cache\_logs\2019-11-06T17_36_28_872Z-debug.log
````

**Comment by mandaputtra** [comment]
Oh thats NODE_ENV not recognized, please try [this](https://stackoverflow.com/a/54115896/5672961).  That error are common on windows.

You can close your issue if this was resolved

**Comment by chella1cm** [comment]
Thanks, It worked. I installed this module "npm install -g win-node-env" and it fixed that. 😊
