### ISSUE TITLE
Image not put in Firefox's cache ?

### ISSUE THREAD

**Issue by mishka81** [ayastreb/bandwidth-hero#40]
Hi,

Image on this webpage : https://humbkr.com/
is not put in cache by Firefox (74.0)
In dev tools, a new request is made to proxy every time I reload the page :

![image](https://user-images.githubusercontent.com/2773527/77845302-1e9bda00-71ae-11ea-9c3e-da0bcb606f89.png)

Seems OK on Chrome :

![image](https://user-images.githubusercontent.com/2773527/77845325-54d95980-71ae-11ea-947c-dbdc1875633f.png)

Thanks in advance for your support.

**Comment by vosian** [comment]
I see that the image is served from cache if you use the address bar to re-access the site, but is loaded again when you use f5 or control-r. If response headers had something like Cache-Control: immutable, then it'd probably work with reload buttons, but I don't know if it could cause problems elsewhere.

**Comment by mishka81** [comment]
you're right.
I consider this is working properly, thanks.
