### ISSUE TITLE
All image turned to black-white

### ISSUE THREAD

**Issue by dupontjoy** [ayastreb/bandwidth-hero#5]
Is it possible to add some settings so we can choose the compression degree?
eg: 
ultra -- highest compression degree, turn images to black-white mode like it does now
medium -- slightly compress images, remain the original color but with lower quality

**Comment by ayastreb** [comment]
Yes, at the moment it's just hard-coded as 40% b/w image.
I planned to add more user control in "compression settings" somewhere in the future.
I'll try to implement it soon.

**Comment by jugi1** [comment]
I support adding fre degrees also.
I would be great

**Comment by KaddishSaint** [comment]
Hey, I really enjoyed your extension. My suggestion is to create an option where you reduce the quality of the images, but not to the starting point of the grayscale. A reduction in quality, but at least keep the color of them. Congrats on the job!

**Comment by ayastreb** [comment]
I've just released v1.1.7 - should be available in Chrome & Firefox soon.
New version has checkbox to enable/disable black&white conversion and also a separate dropdown to choose compression level (from JPG 20 to JPG 80).

Let me know if it helps you.

**Comment by dupontjoy** [comment]
thanks, that's much better



dupontjoy@163.com
 
From: Anatoliy Yastreb
Date: 2017-10-16 18:45
To: ayastreb/bandwidth-hero
CC: 玄清介; Author
Subject: Re: [ayastreb/bandwidth-hero] All image turned to black-white (#5)
I've just released v1.1.7 - should be available in Chrome & Firefox soon.
New version has checkbox to enable/disable black&white conversion and also a separate dropdown to choose compression level (from JPG 20 to JPG 80).
Let me know if it helps you.

**Comment by ayastreb** [comment]
Awesome! Please, leave a review for the extensoion in Google Chrome Store or Firefox Addons if you like it :)
