### ISSUE TITLE
Firefox on Android Support 57+

### ISSUE THREAD

**Issue by mrdokenny** [ayastreb/bandwidth-hero#6]
Hey, thanks for this extension. It works fine on Firefox Desktop but on Firefox Android Beta 57+, it doesn't seem to work. The popup is able to open but nothing gets compressed.

Are you using anything that's not available yet in Firefox Android?

https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Browser_support_for_JavaScript_APIs

I noticed that you used `chrome.storage.sync` which is not available for Firefox Android yet.

**Comment by ayastreb** [comment]
thanks for reporting! I haven't tested it on Android, and yes it uses `chrome.storage.sync` :)
I'll try to find an alternative and fix it.

**Comment by mrdokenny** [comment]
@ayastreb Thanks, just so you know. Popups don't work correctly in the current release 56, so I recommend testing on 57+. 

https://developer.mozilla.org/en-US/docs/Tools/Remote_Debugging/Debugging_Firefox_for_Android_with_WebIDE

**Comment by ayastreb** [comment]
Should be fixed now in 1.1.6 - it was `storage.sync` and `browserAction.setIcon` 😀
Pls, let me know if it works ok for you too.

**Comment by mrdokenny** [comment]
Yes, I can confirm it working on Android. Thanks. 

Though I have another problem that I'll create an issue for.
